// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { CandyPosition, CandyPositionTableId } from "./tables/CandyPosition.sol";
import { CandyBalance, CandyBalanceTableId } from "./tables/CandyBalance.sol";
import { Health, HealthTableId } from "./tables/Health.sol";
import { KillStreak, KillStreakTableId } from "./tables/KillStreak.sol";
