// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICollectSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICollectSystem {
  function candyworld_CollectSystem_collect(uint32 x, uint32 y) external;
}
