// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Spawned, SpawnedTableId } from "./tables/Spawned.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
